In [13]:
import os

from dotenv import load_dotenv

load_dotenv()
token = os.environ["HF_TOKEN"]

In [15]:
from datasets import load_dataset

print("Streaming sample data from Hugging Face...")

# Stream the metadata JSONL file without using the deprecated dataset script.
dataset = load_dataset(
    "json",
    data_files={
        "full": (
            "hf://datasets/McAuley-Lab/Amazon-Reviews-2023/"
            "raw/meta_categories/meta_Sports_and_Outdoors.jsonl"
        )
    },
    split="full",
    streaming=True,
    token=token,
)

Streaming sample data from Hugging Face...

In [33]:
import pandas as pd

# Convert a small streamed sample to a DataFrame for inspection.
sample_df = pd.DataFrame(list(dataset.take(1000)))
sample_df.head(5)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,NaN,Sure-Grip Zombie Wheels Low 59mm 4 Pack,4.5,84,"[Pre-packaged in sets of 4, Low profile 59mm x...",[All Zombie wheels are made in the USA. Zombie...,55.00,[{'thumb': 'https://m.media-amazon.com/images/...,[],Sure-Grip,"[Sports & Outdoors, Sports, Skates, Skateboard...",{'Item Package Dimensions L x W x H': '4.49 x ...,B01HDXC8AG,None,NaN,None
1,NaN,USGI Wet Weather Bag (Fоur Paсk),4.2,14,[],[Wet Wetaher bag US Military 4 pack],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'USGI Waterproof Bag | Willy Peter ...,USGI,"[Sports & Outdoors, Sports, Boating & Sailing,...",{'Best Sellers Rank': {'Sports & Outdoors': 96...,B07R5BQ4YD,None,NaN,None
2,NaN,NHL San Jose Sharks Team Logo Post Earrings,4.5,28,"[100% Synthetic, Imported, Adorable Post Earri...",[Complete your game day outfit with these cute...,18.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aminco,"[Sports & Outdoors, Fan Shop, Jewelry & Watche...",{'Item Package Dimensions L x W x H': '2.5 x 2...,B003K8GZ7G,None,NaN,None
3,Sports & Outdoors,Bont Skates - Prostar Purple Suede Professiona...,4.2,36,[Roller Skates are not like your average shoe....,[],209.00,[{'thumb': 'https://m.media-amazon.com/images/...,[],Bont,"[Sports & Outdoors, Sports, Skates, Skateboard...","{'Size': 'Bont 5', 'Color': 'Purple', 'Brand':...",B08GC4GBWB,None,NaN,None
4,Sports & Outdoors,Team Golf Alamaba Crimson Tide Embroidered Tow...,5.0,3,"[Cotton, Tri-fold golf towel is embroidered wi...",[Keep your clubs clean while supporting your f...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Team Golf,"[Sports & Outdoors, Fan Shop, Sports Equipment...","{'Color': 'Alabama Crimson Tide', 'Brand': 'Te...",B07BYV947H,None,NaN,None

In [25]:
sample_df['bought_together'].unique()

array([None], dtype=object)

In [26]:
sample_df['subtitle'].unique()

<ArrowStringArray>
[nan, 'Misc.']
Length: 2, dtype: str

In [27]:
sample_df['author'].unique()

array([None], dtype=object)

In [34]:
sample_df.drop(columns=['bought_together', 'subtitle', 'author', 'images', 'videos'], inplace=True)

In [30]:
sample_df

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin
0,NaN,Sure-Grip Zombie Wheels Low 59mm 4 Pack,4.5,84,"[Pre-packaged in sets of 4, Low profile 59mm x...",[All Zombie wheels are made in the USA. Zombie...,55.00,[{'thumb': 'https://m.media-amazon.com/images/...,[],Sure-Grip,"[Sports & Outdoors, Sports, Skates, Skateboard...",{'Item Package Dimensions L x W x H': '4.49 x ...,B01HDXC8AG
1,NaN,USGI Wet Weather Bag (Fоur Paсk),4.2,14,[],[Wet Wetaher bag US Military 4 pack],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'USGI Waterproof Bag | Willy Peter ...,USGI,"[Sports & Outdoors, Sports, Boating & Sailing,...",{'Best Sellers Rank': {'Sports & Outdoors': 96...,B07R5BQ4YD
2,NaN,NHL San Jose Sharks Team Logo Post Earrings,4.5,28,"[100% Synthetic, Imported, Adorable Post Earri...",[Complete your game day outfit with these cute...,18.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aminco,"[Sports & Outdoors, Fan Shop, Jewelry & Watche...",{'Item Package Dimensions L x W x H': '2.5 x 2...,B003K8GZ7G
3,Sports & Outdoors,Bont Skates - Prostar Purple Suede Professiona...,4.2,36,[Roller Skates are not like your average shoe....,[],209.00,[{'thumb': 'https://m.media-amazon.com/images/...,[],Bont,"[Sports & Outdoors, Sports, Skates, Skateboard...","{'Size': 'Bont 5', 'Color': 'Purple', 'Brand':...",B08GC4GBWB
4,Sports & Outdoors,Team Golf Alamaba Crimson Tide Embroidered Tow...,5.0,3,"[Cotton, Tri-fold golf towel is embroidered wi...",[Keep your clubs clean while supporting your f...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Team Golf,"[Sports & Outdoors, Fan Shop, Sports Equipment...","{'Color': 'Alabama Crimson Tide', 'Brand': 'Te...",B07BYV947H
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Sports & Outdoors,Oceanic Geo 2.0 Air/Nitrox Computer Watch,4.5,212,"[2 nitrox mixes to 100% oxygen, deep stop with...","[4 operating modes: watch (alternate time, chr...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Shearwater Dive Computer - Unboxin...,Oceanic,"[Sports & Outdoors, Sports, Water Sports, Divi...",{'Item Package Dimensions L x W x H': '5.43 x ...,B0037UVVZI
996,AMAZON FASHION,NCAA Women's Loose French Terry Hood,4.2,37,"[70% Cotton/20% Polyester/10% Rayon, Imported,...",[],49.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Ouray Sportswear,"[Sports & Outdoors, Fan Shop, Clothing, Sweats...","{'Item Weight': '1 Pounds', 'Date First Availa...",B01ISZB494
997,Sports & Outdoors,"WILSON NCAA Copia Due Soccer Ball, Orange - Si...",4.2,64,"[Replica design of the Forte Fybrid, 32-panel,...",[The NCAA Copia Due replica game ball offers t...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],WILSON,"[Sports & Outdoors, Sports, Team Sports, Socce...","{'Brand': 'WILSON', 'Material': 'Synthetic', '...",B00EE2EL3M
998,Sports & Outdoors,Easton 2015 YB15MKT MAKO TORQ -10 Youth Baseba...,3.8,55,"[Ultra-thin 29/32"" composite handle with Torq ...","[SHORTER TO THE ZONE, LONGER THRU THE ZONE. Sq...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Easton,"[Sports & Outdoors, Sports, Team Sports, Softb...","{'Size': '28-Inch/18-Ounce', 'Sport Type': 'Ba...",B00KNM8ZXO
999,Sports & Outdoors,NCAA Texas Longhorns 2-Sided 3-by-5 Foot Flag ...,3.5,7,"[100% polyester, Printed on both sides, 2 heav...",[Show your school spirit by hanging this 3-ft ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],BSI,"[Sports & Outdoors, Fan Shop, Patio, Lawn & Ga...",{'Item Package Dimensions L x W x H': '10.4 x ...,B000TBFS2K