In [39]:
import os

from dotenv import load_dotenv

load_dotenv()
token = os.environ["HF_TOKEN"]

Load meta cagetories dataset for adevnture sports

In [46]:
from datasets import load_dataset

print("Streaming sample data from Hugging Face...")

# Stream the metadata JSONL file without using the deprecated dataset script.
meta_dataset = load_dataset(
    "json",
    data_files={
        "full": (
            "hf://datasets/McAuley-Lab/Amazon-Reviews-2023/"
            "raw/meta_categories/meta_Sports_and_Outdoors.jsonl"
        )
    },
    split="full",
    streaming=True,
    token=token,
)

Streaming sample data from Hugging Face...

In [47]:
import pandas as pd

# Convert a small streamed sample to a DataFrame for inspection.
sample_meta_df = pd.DataFrame(list(meta_dataset.take(1000)))
sample_meta_df.head(5)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,NaN,Sure-Grip Zombie Wheels Low 59mm 4 Pack,4.5,84,"[Pre-packaged in sets of 4, Low profile 59mm x...",[All Zombie wheels are made in the USA. Zombie...,55.00,[{'thumb': 'https://m.media-amazon.com/images/...,[],Sure-Grip,"[Sports & Outdoors, Sports, Skates, Skateboard...",{'Item Package Dimensions L x W x H': '4.49 x ...,B01HDXC8AG,None,NaN,None
1,NaN,USGI Wet Weather Bag (Fоur Paсk),4.2,14,[],[Wet Wetaher bag US Military 4 pack],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'USGI Waterproof Bag | Willy Peter ...,USGI,"[Sports & Outdoors, Sports, Boating & Sailing,...",{'Best Sellers Rank': {'Sports & Outdoors': 96...,B07R5BQ4YD,None,NaN,None
2,NaN,NHL San Jose Sharks Team Logo Post Earrings,4.5,28,"[100% Synthetic, Imported, Adorable Post Earri...",[Complete your game day outfit with these cute...,18.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aminco,"[Sports & Outdoors, Fan Shop, Jewelry & Watche...",{'Item Package Dimensions L x W x H': '2.5 x 2...,B003K8GZ7G,None,NaN,None
3,Sports & Outdoors,Bont Skates - Prostar Purple Suede Professiona...,4.2,36,[Roller Skates are not like your average shoe....,[],209.00,[{'thumb': 'https://m.media-amazon.com/images/...,[],Bont,"[Sports & Outdoors, Sports, Skates, Skateboard...","{'Size': 'Bont 5', 'Color': 'Purple', 'Brand':...",B08GC4GBWB,None,NaN,None
4,Sports & Outdoors,Team Golf Alamaba Crimson Tide Embroidered Tow...,5.0,3,"[Cotton, Tri-fold golf towel is embroidered wi...",[Keep your clubs clean while supporting your f...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Team Golf,"[Sports & Outdoors, Fan Shop, Sports Equipment...","{'Color': 'Alabama Crimson Tide', 'Brand': 'Te...",B07BYV947H,None,NaN,None

In [48]:
sample_meta_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   main_category    934 non-null    str
 1   title            1000 non-null   str
 2   average_rating   1000 non-null   float64
 3   rating_number    1000 non-null   int64
 4   features         1000 non-null   object
 5   description      1000 non-null   object
 6   price            482 non-null    float64
 7   images           1000 non-null   object
 8   videos           1000 non-null   object
 9   store            986 non-null    str
 10  categories       1000 non-null   object
 11  details          1000 non-null   object
 12  parent_asin      1000 non-null   str
 13  bought_together  0 non-null      object
 14  subtitle         1 non-null      str
 15  author           0 non-null      object
dtypes: float64(2), int64(1), object(8), str(5)
memory usage: 243.5+ KB

In [49]:
sample_meta_df.describe()

       average_rating  rating_number        price
count     1000.000000    1000.000000   482.000000
mean         4.295900     545.725000    51.194108
std          0.605442    2066.038307    90.008772
min          1.000000       1.000000     2.990000
25%          4.000000       7.000000    13.990000
50%          4.400000      29.000000    23.990000
75%          4.700000     171.250000    49.967500
max          5.000000   27135.000000  1124.700000

In [50]:
sample_meta_df['bought_together'].unique()

array([None], dtype=object)

In [52]:
sample_meta_df['subtitle'].unique()

<ArrowStringArray>
[nan, 'Misc.']
Length: 2, dtype: str

In [53]:
sample_meta_df['author'].unique()

array([None], dtype=object)

In [ ]:
sample_meta_df.drop(columns=['bought_together', 'subtitle', 'author', 'images', 'videos'], inplace=True)

In [ ]:
sample_meta_df

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin
0,NaN,Sure-Grip Zombie Wheels Low 59mm 4 Pack,4.5,84,"[Pre-packaged in sets of 4, Low profile 59mm x...",[All Zombie wheels are made in the USA. Zombie...,55.00,[{'thumb': 'https://m.media-amazon.com/images/...,[],Sure-Grip,"[Sports & Outdoors, Sports, Skates, Skateboard...",{'Item Package Dimensions L x W x H': '4.49 x ...,B01HDXC8AG
1,NaN,USGI Wet Weather Bag (Fоur Paсk),4.2,14,[],[Wet Wetaher bag US Military 4 pack],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'USGI Waterproof Bag | Willy Peter ...,USGI,"[Sports & Outdoors, Sports, Boating & Sailing,...",{'Best Sellers Rank': {'Sports & Outdoors': 96...,B07R5BQ4YD
2,NaN,NHL San Jose Sharks Team Logo Post Earrings,4.5,28,"[100% Synthetic, Imported, Adorable Post Earri...",[Complete your game day outfit with these cute...,18.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aminco,"[Sports & Outdoors, Fan Shop, Jewelry & Watche...",{'Item Package Dimensions L x W x H': '2.5 x 2...,B003K8GZ7G
3,Sports & Outdoors,Bont Skates - Prostar Purple Suede Professiona...,4.2,36,[Roller Skates are not like your average shoe....,[],209.00,[{'thumb': 'https://m.media-amazon.com/images/...,[],Bont,"[Sports & Outdoors, Sports, Skates, Skateboard...","{'Size': 'Bont 5', 'Color': 'Purple', 'Brand':...",B08GC4GBWB
4,Sports & Outdoors,Team Golf Alamaba Crimson Tide Embroidered Tow...,5.0,3,"[Cotton, Tri-fold golf towel is embroidered wi...",[Keep your clubs clean while supporting your f...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Team Golf,"[Sports & Outdoors, Fan Shop, Sports Equipment...","{'Color': 'Alabama Crimson Tide', 'Brand': 'Te...",B07BYV947H
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Sports & Outdoors,Oceanic Geo 2.0 Air/Nitrox Computer Watch,4.5,212,"[2 nitrox mixes to 100% oxygen, deep stop with...","[4 operating modes: watch (alternate time, chr...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Shearwater Dive Computer - Unboxin...,Oceanic,"[Sports & Outdoors, Sports, Water Sports, Divi...",{'Item Package Dimensions L x W x H': '5.43 x ...,B0037UVVZI
996,AMAZON FASHION,NCAA Women's Loose French Terry Hood,4.2,37,"[70% Cotton/20% Polyester/10% Rayon, Imported,...",[],49.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Ouray Sportswear,"[Sports & Outdoors, Fan Shop, Clothing, Sweats...","{'Item Weight': '1 Pounds', 'Date First Availa...",B01ISZB494
997,Sports & Outdoors,"WILSON NCAA Copia Due Soccer Ball, Orange - Si...",4.2,64,"[Replica design of the Forte Fybrid, 32-panel,...",[The NCAA Copia Due replica game ball offers t...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],WILSON,"[Sports & Outdoors, Sports, Team Sports, Socce...","{'Brand': 'WILSON', 'Material': 'Synthetic', '...",B00EE2EL3M
998,Sports & Outdoors,Easton 2015 YB15MKT MAKO TORQ -10 Youth Baseba...,3.8,55,"[Ultra-thin 29/32"" composite handle with Torq ...","[SHORTER TO THE ZONE, LONGER THRU THE ZONE. Sq...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Easton,"[Sports & Outdoors, Sports, Team Sports, Softb...","{'Size': '28-Inch/18-Ounce', 'Sport Type': 'Ba...",B00KNM8ZXO
999,Sports & Outdoors,NCAA Texas Longhorns 2-Sided 3-by-5 Foot Flag ...,3.5,7,"[100% polyester, Printed on both sides, 2 heav...",[Show your school spirit by hanging this 3-ft ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],BSI,"[Sports & Outdoors, Fan Shop, Patio, Lawn & Ga...",{'Item Package Dimensions L x W x H': '10.4 x ...,B000TBFS2K

In [67]:
sample_meta_df['features'][0]

['Pre-packaged in sets of 4',
 'Low profile 59mm x 38mm',
 '89a w/purple hub, 92a w/black hub, 95a w/red hub, 98a w/green hub',
 'Made in the U.S.A.',
 'Anodized Aluminum Hub']

In [68]:
sample_meta_df['description'][0]

['All Zombie wheels are made in the USA. Zombie wheels feature anodized aluminum hubs for maximum durability and precise feel while maintaining rock solid stability. This allows our unique urethane compounds to deliver all your power to the floor. Choose the Zombie combination that fits your skating style and surface. Zombie Aluminum Core – Designed in house and manufactured using state of the art machining technology. What makes this different from other aluminum cores? The Zombie core is machined from a solid billet of aluminum, using the same manufacturing processes as we use to make our famous Power Trac racing plates. This increases strength and allows us to machine the hub to a tighter tolerance than any other hub on the market. Creating the perfect fit between bearing and inner core. Cores are then treated with a special anodizing process to increase hub durability and urethane bonding. This technology is unique to the Zombie wheel line. Zombie Insane Urethane – Specially formulated to our exact specifications that were developed from 75 years in the skate wheel business. What makes this wheel different from the rest? All wheels are poured using a precise time schedule to ensue product quality throughout the range. Typically wheels are poured over time, sometimes days. This can change the characteristic of a wheel poured one day vs. another or even morning vs. afternoon. This timing is what make the Zombie wheel the most unique wheel on the market. Due to production limitations certain product characteristics might vary slightly. For more information please contact the manufacture.']

Load Review categories dataset for Adventure sports

In [54]:
from datasets import load_dataset

print("Streaming sample data from Hugging Face...")

# Stream the metadata JSONL file without using the deprecated dataset script.
review_dataset = load_dataset(
    "json",
    data_files={
        "full": (
            "hf://datasets/McAuley-Lab/Amazon-Reviews-2023/"
            "raw/review_categories/Sports_and_Outdoors.jsonl"
        )
    },
    split="full",
    streaming=True,
    token=token,
)

Streaming sample data from Hugging Face...

In [62]:
import pandas as pd

# Convert a small streamed sample to a DataFrame for inspection.
sample_review_df = pd.DataFrame(list(review_dataset.take(1000)))
sample_review_df.head(5)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Crazy comfy!,Not gonna lie- they are not much to look at. L...,[],B07F3BDT8T,B0BGFR76CF,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1677321053520,8,True
1,5.0,Excellent!,I love it. Pretty!,[],B00NXQLFQQ,B00NXQLFQQ,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1523093771676,0,True
2,5.0,Best saddle pads,Huge fan of B Vertigo and this dressage pad do...,[],B08SVPR266,B0957WLR63,AGGZ357AO26RQZVRLGU4D4N52DZQ,1653526919105,0,True
3,5.0,Perfect repair kit,"I have a great Weaver halter. Recently, the Ch...",[],B00IET8S80,B00IET8S80,AGGZ357AO26RQZVRLGU4D4N52DZQ,1627330911189,0,True
4,5.0,Works great,This was great for a slightly too-short girth!...,[],B00DV0MKUY,B01C2SW7XA,AGGZ357AO26RQZVRLGU4D4N52DZQ,1617831811976,0,True

In [63]:
sample_review_df.describe()

            rating     timestamp  helpful_vote
count  1000.000000  1.000000e+03   1000.000000
mean      4.302000  1.566964e+12      1.140000
std       1.128747  8.110876e+10      6.245591
min       1.000000  1.239589e+12      0.000000
25%       4.000000  1.528062e+12      0.000000
50%       5.000000  1.581316e+12      0.000000
75%       5.000000  1.626977e+12      1.000000
max       5.000000  1.678482e+12    135.000000

In [64]:
sample_review_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating             1000 non-null   float64
 1   title              1000 non-null   str
 2   text               1000 non-null   str
 3   images             1000 non-null   object
 4   asin               1000 non-null   str
 5   parent_asin        1000 non-null   str
 6   user_id            1000 non-null   str
 7   timestamp          1000 non-null   int64
 8   helpful_vote       1000 non-null   int64
 9   verified_purchase  1000 non-null   bool
dtypes: bool(1), float64(1), int64(2), object(1), str(5)
memory usage: 399.0+ KB

In [65]:
sample_review_df.shape

(1000, 10)

False